#!/usr/bin/env php

<?php

set_time_limit(0);

$drupalRoot = realpath(dirname(dirname(__DIR__)));

$loader = require_once $drupalRoot . '/core/vendor/autoload.php';

use Drupal\Core\Command\RunTestsCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new RunTestsCommand(null, $drupalRoot));
$application->run();
